#!/bin/sh

# Install vim-plug for NeoVim
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# install vim-plug
# if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
#     curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
#             https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi

# install fzf
# if [ ! -e $HOME/.fzf/fzf ]; then
#     git clone https://github.com/junegunn/fzf.git ~/.fzf \
#             && ~/.fzf/install
# fi

# install antigen
# if [ ! -e $HOME/.antigen/antigen.zsh ]; then
#   git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
# fi

# install and clean vim plugins using vim-plug
# vim +PlugInstall +PlugClean! +qa

# # TMUX
# if [ ! -e $HOME/.tmux/plugins/tpm/tpm ]; then
#   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# fi
