#!/bin/sh

# install fzf
if [ ! -e $HOME/.fzf/fzf ]; then
    git clone https://github.com/junegunn/fzf.git ~/.fzf \
            && ~/.fzf/install
fi

# install antigen
if [ ! -e $HOME/.antigen/antigen.zsh ]; then
  git clone https://github.com/zsh-users/antigen.git $HOME/.antigen
fi