# nvm
export NVM_DIR="/Users/bassam/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# z
. `brew --prefix`/etc/profile.d/z.sh

# ~/.bin directory
export PATH="$HOME/.bin:$PATH"

# Golang
export GOPATH=$HOME/.go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# Rust (for code completion)
export RUST_SRC_PATH=$HOME/.rust/src
